# Generated by Django 3.1 on 2022-03-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_modelholder_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_super_teacher',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_teacher',
        ),
    ]
