# Generated by Django 3.1 on 2022-03-10 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220303_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelholder',
            old_name='search',
            new_name='name',
        ),
    ]
